#!/usr/bin/env python
"""
Companion script for 5a_paper_plots.ipynb: refreshes the two data-aggregation
caches the notebook's Figure 5 (performance summary) and Figure 6 (individual
forcing-agent effects) read - data/plotting/optimal_all_agents_subset.pkl and
the y_hat/y_true_ind_effects.pkl trio. Neither is regenerated by default when
the notebook runs (it just reads the existing cache), since both involve
training several MLP emulators (K=400 SGD steps each) from upstream inverse-
optimization checkpoints - this script exists so that refresh can be
scheduled instead of triggered by hand-calling
utils_inverse.regenerate_fig5_all_agents_cache()/
regenerate_fig6_individual_effects_cache() from a notebook cell.

Usage:
    python 5a_paper_plots.py             # regenerate both
    python 5a_paper_plots.py --figure 5  # just Figure 5's cache
    python 5a_paper_plots.py --figure 6  # just Figure 6's cache
"""
import argparse
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
os.chdir(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))

import utils_inverse


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--figure", choices=["5", "6"], default=None,
                         help="Regenerate only this figure's cache (default: regenerate both)")
    args = parser.parse_args()

    if args.figure in (None, "5"):
        utils_inverse.regenerate_fig5_all_agents_cache()
        print("Saved data/plotting/optimal_all_agents_subset.pkl")
    if args.figure in (None, "6"):
        utils_inverse.regenerate_fig6_individual_effects_cache()
        print("Saved data/plotting/y_hat_baseline_ind_effects.pkl, "
              "y_true_ind_effects.pkl, y_hat_ind_effects.pkl")


if __name__ == "__main__":
    main()
