#!/usr/bin/env python
# ============================================================
# Author: Christopher B. Womack
# Coding assistance provided by Claude Sonnet 5 and Gemini 3.1 Pro.
# Responsibility for the final manuscript/code lies entirely with the authors.
# GAI tools are not listed as authors and do not bear responsibility for the
# final outcomes.
# ============================================================

"""
Companion script for supplementary_notebooks/SI_plots.ipynb: refreshes the
single-agent (N2O/Sulfur/BC) optimal-emulator NRMSE cache
(data/SI_results/extended_results/optimal_<agent>_only.pkl) that the SI
extended-results stacked-bar figure reads. Not regenerated by default when
the notebook runs (it just reads the existing cache), since it trains a
fresh MLP emulator (K=400 SGD steps) per agent per training-checkpoint group
from upstream inverse-optimization checkpoints - this script exists so that
refresh can be scheduled instead of triggered by hand-calling
utils_inverse.regenerate_SI_extended_results_cache() from a notebook cell.

Note: the CO2/CH4 entries this figure also reads
(data/SI_results/extended_results/{baseline,optimal}_{co2,ch4}_only.pkl) were
produced by a separate, untracked process outside this notebook/script and
are not regenerated here - matches the original notebook, which only ever
looped over N2O/Sulfur/BC.

Usage:
    python SI_plots.py
"""
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
os.chdir(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))

import utils_inverse


def main():
    utils_inverse.regenerate_SI_extended_results_cache()
    print("Saved data/SI_results/extended_results/optimal_{n2o,Sulfur,BC}_only.pkl")


if __name__ == "__main__":
    main()
